services:
  - type: web
    name: opengym
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATA_DIR
        value: /tmp/data
      - key: RP_NAME
        value: openGym

